program: run_wandb.py
method: grid
name: sweep-embed-fuse
metric:
  goal: minimize
  name: best_val_rmse
parameters:
  hid_dim:
    values: [64, 128]
  lr:
    values: [1e-2, 1e-3]
  epochs:
    value: 2000
  patience:
    value: 5
  wd:
    value: 1e-2
  dropout:
    value: 0.5
  nlayers:
    values: [2, 3]
  split_args:
    value:
      train_size: 0.6
      valid_size: 0.2
      test_size: 0.2
  use_wandb:
    value: true
  model_name:
    values: [GCN_fuse_embed, SAGE_fuse_embed, SGC_fuse_embed]
  # modality:
  #   values: [sc, fc]
  # ratio:
  #   values: [0.2, 0.8]
  ratio_sc:
    values: [0.2, 0.8]
  ratio_fc:
    values: [0.2, 0.8]
  reduce:
    value: mean
  reduce_fuse_embed:
    values: [mean, concat, sum]
