program: run_wandb.py
method: grid
name: sweep
metric:
  goal: minimize
  name: best_val_rmse
parameters:
  hid_dim:
    values: [64, 128]
  lr:
    values: [1e-2, 1e-3]
  epochs:
    value: 2000
  patience:
    value: 5
  wd:
    value: 1e-2
  dropout:
    value: 0.5
  nlayers:
    values: [2, 3, 4]
  split_args:
    value:
      train_size: 0.6
      valid_size: 0.2
      test_size: 0.2
  use_wandb:
    value: true
  model_name:
    value: MHGCN
  # modality:
  #   values: [sc, fc]
  # ratio:
  #   values: [0.2, 0.8]
  ratio_sc:
    value: 0.1
  ratio_fc:
    value: 0.5
  reduce:
    value: mean
